#!/bin/bash
bash ./scripts/OpenPowerSystem_script/TemporalFusionTransformer_OpenPowerSystem_load.sh
bash ./scripts/OpenPowerSystem_script/TemporalFusionTransformer_OpenPowerSystem_price.sh
bash ./scripts/OpenPowerSystem_script/TemporalFusionTransformer_OpenPowerSystem_solar.sh
bash ./scripts/OpenPowerSystem_script/TemporalFusionTransformer_OpenPowerSystem_wind.sh
